<?php

namespace Database\Seeders;

use App\Models\backend\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->data() as $item) {
            Country::firstOrCreate([
                'id' => $item['id']
            ], $item);
        }

    //     $countries = array(
            // array('iso2' => 'US', 'short_name' => 'United States'),
            // array('iso2' => 'CA', 'short_name' => 'Canada'),
            // array('iso2' => 'AF', 'short_name' => 'Afghanistan'),
            // array('iso2' => 'AL', 'short_name' => 'Albania'),
            // array('iso2' => 'DZ', 'short_name' => 'Algeria'),
            // array('iso2' => 'AS', 'short_name' => 'American Samoa'),
            // array('iso2' => 'AD', 'short_name' => 'Andorra'),
            // array('iso2' => 'AO', 'short_name' => 'Angola'),
            // array('iso2' => 'AI', 'short_name' => 'Anguilla'),
            // array('iso2' => 'AQ', 'short_name' => 'Antarctica'),
            // array('iso2' => 'AG', 'short_name' => 'Antigua and/or Barbuda'),
            // array('iso2' => 'AR', 'short_name' => 'Argentina'),
            // array('iso2' => 'AM', 'short_name' => 'Armenia'),
            // array('iso2' => 'AW', 'short_name' => 'Aruba'),
            // array('iso2' => 'AU', 'short_name' => 'Australia'),
            // array('iso2' => 'AT', 'short_name' => 'Austria'),
            // array('iso2' => 'AZ', 'short_name' => 'Azerbaijan'),
            // array('iso2' => 'BS', 'short_name' => 'Bahamas'),
            // array('iso2' => 'BH', 'short_name' => 'Bahrain'),
            // array('iso2' => 'BD', 'short_name' => 'Bangladesh'),
            // array('iso2' => 'BB', 'short_name' => 'Barbados'),
            // array('iso2' => 'BY', 'short_name' => 'Belarus'),
            // array('iso2' => 'BE', 'short_name' => 'Belgium'),
            // array('iso2' => 'BZ', 'short_name' => 'Belize'),
            // array('iso2' => 'BJ', 'short_name' => 'Benin'),
            // array('iso2' => 'BM', 'short_name' => 'Bermuda'),
            // array('iso2' => 'BT', 'short_name' => 'Bhutan'),
            // array('iso2' => 'BO', 'short_name' => 'Bolivia'),
            // array('iso2' => 'BA', 'short_name' => 'Bosnia and Herzegovina'),
            // array('iso2' => 'BW', 'short_name' => 'Botswana'),
            // array('iso2' => 'BV', 'short_name' => 'Bouvet Island'),
            // array('iso2' => 'BR', 'short_name' => 'Brazil'),
            // array('iso2' => 'IO', 'short_name' => 'British lndian Ocean Territory'),
            // array('iso2' => 'BN', 'short_name' => 'Brunei Darussalam'),
            // array('iso2' => 'BG', 'short_name' => 'Bulgaria'),
            // array('iso2' => 'BF', 'short_name' => 'Burkina Faso'),
            // array('iso2' => 'BI', 'short_name' => 'Burundi'),
            // array('iso2' => 'KH', 'short_name' => 'Cambodia'),
            // array('iso2' => 'CM', 'short_name' => 'Cameroon'),
            // array('iso2' => 'CV', 'short_name' => 'Cape Verde'),
            // array('iso2' => 'KY', 'short_name' => 'Cayman Islands'),
            // array('iso2' => 'CF', 'short_name' => 'Central African Republic'),
            // array('iso2' => 'TD', 'short_name' => 'Chad'),
            // array('iso2' => 'CL', 'short_name' => 'Chile'),
            // array('iso2' => 'CN', 'short_name' => 'China'),
            // array('iso2' => 'CX', 'short_name' => 'Christmas Island'),
            // array('iso2' => 'CC', 'short_name' => 'Cocos (Keeling) Islands'),
            // array('iso2' => 'CO', 'short_name' => 'Colombia'),
            // array('iso2' => 'KM', 'short_name' => 'Comoros'),
            // array('iso2' => 'CG', 'short_name' => 'Congo'),
            // array('iso2' => 'CK', 'short_name' => 'Cook Islands'),
            // array('iso2' => 'CR', 'short_name' => 'Costa Rica'),
            // array('iso2' => 'HR', 'short_name' => 'Croatia (Hrvatska)'),
            // array('iso2' => 'CU', 'short_name' => 'Cuba'),
            // array('iso2' => 'CY', 'short_name' => 'Cyprus'),
            // array('iso2' => 'CZ', 'short_name' => 'Czech Republic'),
            // array('iso2' => 'CD', 'short_name' => 'Democratic Republic of Congo'),
            // array('iso2' => 'DK', 'short_name' => 'Denmark'),
            // array('iso2' => 'DJ', 'short_name' => 'Djibouti'),
            // array('iso2' => 'DM', 'short_name' => 'Dominica'),
            // array('iso2' => 'DO', 'short_name' => 'Dominican Republic'),
            // array('iso2' => 'TP', 'short_name' => 'East Timor'),
            // array('iso2' => 'EC', 'short_name' => 'Ecudaor'),
            // array('iso2' => 'EG', 'short_name' => 'Egypt'),
            // array('iso2' => 'SV', 'short_name' => 'El Salvador'),
            // array('iso2' => 'GQ', 'short_name' => 'Equatorial Guinea'),
            // array('iso2' => 'ER', 'short_name' => 'Eritrea'),
            // array('iso2' => 'EE', 'short_name' => 'Estonia'),
            // array('iso2' => 'ET', 'short_name' => 'Ethiopia'),
            // array('iso2' => 'FK', 'short_name' => 'Falkland Islands (Malvinas)'),
            // array('iso2' => 'FO', 'short_name' => 'Faroe Islands'),
            // array('iso2' => 'FJ', 'short_name' => 'Fiji'),
            // array('iso2' => 'FI', 'short_name' => 'Finland'),
            // array('iso2' => 'FR', 'short_name' => 'France'),
            // array('iso2' => 'FX', 'short_name' => 'France, Metropolitan'),
            // array('iso2' => 'GF', 'short_name' => 'French Guiana'),
            // array('iso2' => 'PF', 'short_name' => 'French Polynesia'),
            // array('iso2' => 'TF', 'short_name' => 'French Southern Territories'),
            // array('iso2' => 'GA', 'short_name' => 'Gabon'),
            // array('iso2' => 'GM', 'short_name' => 'Gambia'),
            // array('iso2' => 'GE', 'short_name' => 'Georgia'),
            // array('iso2' => 'DE', 'short_name' => 'Germany'),
            // array('iso2' => 'GH', 'short_name' => 'Ghana'),
            // array('iso2' => 'GI', 'short_name' => 'Gibraltar'),
            // array('iso2' => 'GR', 'short_name' => 'Greece'),
            // array('iso2' => 'GL', 'short_name' => 'Greenland'),
            // array('iso2' => 'GD', 'short_name' => 'Grenada'),
            // array('iso2' => 'GP', 'short_name' => 'Guadeloupe'),
            // array('iso2' => 'GU', 'short_name' => 'Guam'),
            // array('iso2' => 'GT', 'short_name' => 'Guatemala'),
            // array('iso2' => 'GN', 'short_name' => 'Guinea'),
            // array('iso2' => 'GW', 'short_name' => 'Guinea-Bissau'),
            // array('iso2' => 'GY', 'short_name' => 'Guyana'),
            // array('iso2' => 'HT', 'short_name' => 'Haiti'),
            // array('iso2' => 'HM', 'short_name' => 'Heard and Mc Donald Islands'),
            // array('iso2' => 'HN', 'short_name' => 'Honduras'),
            // array('iso2' => 'HK', 'short_name' => 'Hong Kong'),
            // array('iso2' => 'HU', 'short_name' => 'Hungary'),
            // array('iso2' => 'IS', 'short_name' => 'Iceland'),
            // array('iso2' => 'IN', 'short_name' => 'India'),
            // array('iso2' => 'ID', 'short_name' => 'Indonesia'),
            // array('iso2' => 'IR', 'short_name' => 'Iran (Islamic Republic of)'),
            // array('iso2' => 'IQ', 'short_name' => 'Iraq'),
            // array('iso2' => 'IE', 'short_name' => 'Ireland'),
            // array('iso2' => 'IL', 'short_name' => 'Israel'),
            // array('iso2' => 'IT', 'short_name' => 'Italy'),
            // array('iso2' => 'CI', 'short_name' => 'Ivory Coast'),
            // array('iso2' => 'JM', 'short_name' => 'Jamaica'),
            // array('iso2' => 'JP', 'short_name' => 'Japan'),
            // array('iso2' => 'JO', 'short_name' => 'Jordan'),
            // array('iso2' => 'KZ', 'short_name' => 'Kazakhstan'),
            // array('iso2' => 'KE', 'short_name' => 'Kenya'),
            // array('iso2' => 'KI', 'short_name' => 'Kiribati'),
            // array('iso2' => 'KP', 'short_name' => 'Korea, Democratic People\'s Republic of'),
            // array('iso2' => 'KR', 'short_name' => 'Korea, Republic of'),
            // array('iso2' => 'KW', 'short_name' => 'Kuwait'),
            // array('iso2' => 'KG', 'short_name' => 'Kyrgyzstan'),
            // array('iso2' => 'LA', 'short_name' => 'Lao People\'s Democratic Republic'),
            // array('iso2' => 'LV', 'short_name' => 'Latvia'),
            // array('iso2' => 'LB', 'short_name' => 'Lebanon'),
            // array('iso2' => 'LS', 'short_name' => 'Lesotho'),
            // array('iso2' => 'LR', 'short_name' => 'Liberia'),
            // array('iso2' => 'LY', 'short_name' => 'Libyan Arab Jamahiriya'),
            // array('iso2' => 'LI', 'short_name' => 'Liechtenstein'),
            // array('iso2' => 'LT', 'short_name' => 'Lithuania'),
            // array('iso2' => 'LU', 'short_name' => 'Luxembourg'),
            // array('iso2' => 'MO', 'short_name' => 'Macau'),
            // array('iso2' => 'MK', 'short_name' => 'Macedonia'),
            // array('iso2' => 'MG', 'short_name' => 'Madagascar'),
            // array('iso2' => 'MW', 'short_name' => 'Malawi'),
            // array('iso2' => 'MY', 'short_name' => 'Malaysia'),
            // array('iso2' => 'MV', 'short_name' => 'Maldives'),
            // array('iso2' => 'ML', 'short_name' => 'Mali'),
            // array('iso2' => 'MT', 'short_name' => 'Malta'),
            // array('iso2' => 'MH', 'short_name' => 'Marshall Islands'),
            // array('iso2' => 'MQ', 'short_name' => 'Martinique'),
            // array('iso2' => 'MR', 'short_name' => 'Mauritania'),
            // array('iso2' => 'MU', 'short_name' => 'Mauritius'),
            // array('iso2' => 'TY', 'short_name' => 'Mayotte'),
            // array('iso2' => 'MX', 'short_name' => 'Mexico'),
            // array('iso2' => 'FM', 'short_name' => 'Micronesia, Federated States of'),
            // array('iso2' => 'MD', 'short_name' => 'Moldova, Republic of'),
            // array('iso2' => 'MC', 'short_name' => 'Monaco'),
            // array('iso2' => 'MN', 'short_name' => 'Mongolia'),
            // array('iso2' => 'MS', 'short_name' => 'Montserrat'),
            // array('iso2' => 'MA', 'short_name' => 'Morocco'),
            // array('iso2' => 'MZ', 'short_name' => 'Mozambique'),
            // array('iso2' => 'MM', 'short_name' => 'Myanmar'),
            // array('iso2' => 'NA', 'short_name' => 'Namibia'),
            // array('iso2' => 'NR', 'short_name' => 'Nauru'),
            // array('iso2' => 'NP', 'short_name' => 'Nepal'),
            // array('iso2' => 'NL', 'short_name' => 'Netherlands'),
            // array('iso2' => 'AN', 'short_name' => 'Netherlands Antilles'),
            // array('iso2' => 'NC', 'short_name' => 'New Caledonia'),
            // array('iso2' => 'NZ', 'short_name' => 'New Zealand'),
            // array('iso2' => 'NI', 'short_name' => 'Nicaragua'),
            // array('iso2' => 'NE', 'short_name' => 'Niger'),
            // array('iso2' => 'NG', 'short_name' => 'Nigeria'),
            // array('iso2' => 'NU', 'short_name' => 'Niue'),
            // array('iso2' => 'NF', 'short_name' => 'Norfork Island'),
            // array('iso2' => 'MP', 'short_name' => 'Northern Mariana Islands'),
            // array('iso2' => 'NO', 'short_name' => 'Norway'),
            // array('iso2' => 'OM', 'short_name' => 'Oman'),
            // array('iso2' => 'PK', 'short_name' => 'Pakistan'),
            // array('iso2' => 'PW', 'short_name' => 'Palau'),
            // array('iso2' => 'PA', 'short_name' => 'Panama'),
            // array('iso2' => 'PG', 'short_name' => 'Papua New Guinea'),
            // array('iso2' => 'PY', 'short_name' => 'Paraguay'),
            // array('iso2' => 'PE', 'short_name' => 'Peru'),
            // array('iso2' => 'PH', 'short_name' => 'Philippines'),
            // array('iso2' => 'PN', 'short_name' => 'Pitcairn'),
            // array('iso2' => 'PL', 'short_name' => 'Poland'),
            // array('iso2' => 'PT', 'short_name' => 'Portugal'),
            // array('iso2' => 'PR', 'short_name' => 'Puerto Rico'),
            // array('iso2' => 'QA', 'short_name' => 'Qatar'),
            // array('iso2' => 'SS', 'short_name' => 'Republic of South Sudan'),
            // array('iso2' => 'RE', 'short_name' => 'Reunion'),
            // array('iso2' => 'RO', 'short_name' => 'Romania'),
            // array('iso2' => 'RU', 'short_name' => 'Russian Federation'),
            // array('iso2' => 'RW', 'short_name' => 'Rwanda'),
            // array('iso2' => 'KN', 'short_name' => 'Saint Kitts and Nevis'),
            // array('iso2' => 'LC', 'short_name' => 'Saint Lucia'),
            // array('iso2' => 'VC', 'short_name' => 'Saint Vincent and the Grenadines'),
            // array('iso2' => 'WS', 'short_name' => 'Samoa'),
            // array('iso2' => 'SM', 'short_name' => 'San Marino'),
            // array('iso2' => 'ST', 'short_name' => 'Sao Tome and Principe'),
            // array('iso2' => 'SA', 'short_name' => 'Saudi Arabia'),
            // array('iso2' => 'SN', 'short_name' => 'Senegal'),
            // array('iso2' => 'RS', 'short_name' => 'Serbia'),
            // array('iso2' => 'SC', 'short_name' => 'Seychelles'),
            // array('iso2' => 'SL', 'short_name' => 'Sierra Leone'),
            // array('iso2' => 'SG', 'short_name' => 'Singapore'),
            // array('iso2' => 'SK', 'short_name' => 'Slovakia'),
            // array('iso2' => 'SI', 'short_name' => 'Slovenia'),
            // array('iso2' => 'SB', 'short_name' => 'Solomon Islands'),
            // array('iso2' => 'SO', 'short_name' => 'Somalia'),
            // array('iso2' => 'ZA', 'short_name' => 'South Africa'),
            // array('iso2' => 'GS', 'short_name' => 'South Georgia South Sandwich Islands'),
            // array('iso2' => 'ES', 'short_name' => 'Spain'),
            // array('iso2' => 'LK', 'short_name' => 'Sri Lanka'),
            // array('iso2' => 'SH', 'short_name' => 'St. Helena'),
            // array('iso2' => 'PM', 'short_name' => 'St. Pierre and Miquelon'),
            // array('iso2' => 'SD', 'short_name' => 'Sudan'),
            // array('iso2' => 'SR', 'short_name' => 'Suriname'),
            // array('iso2' => 'SJ', 'short_name' => 'Svalbarn and Jan Mayen Islands'),
            // array('iso2' => 'SZ', 'short_name' => 'Swaziland'),
            // array('iso2' => 'SE', 'short_name' => 'Sweden'),
            // array('iso2' => 'CH', 'short_name' => 'Switzerland'),
            // array('iso2' => 'SY', 'short_name' => 'Syrian Arab Republic'),
            // array('iso2' => 'TW', 'short_name' => 'Taiwan'),
            // array('iso2' => 'TJ', 'short_name' => 'Tajikistan'),
            // array('iso2' => 'TZ', 'short_name' => 'Tanzania, United Republic of'),
            // array('iso2' => 'TH', 'short_name' => 'Thailand'),
            // array('iso2' => 'TG', 'short_name' => 'Togo'),
            // array('iso2' => 'TK', 'short_name' => 'Tokelau'),
            // array('iso2' => 'TO', 'short_name' => 'Tonga'),
            // array('iso2' => 'TT', 'short_name' => 'Trinidad and Tobago'),
            // array('iso2' => 'TN', 'short_name' => 'Tunisia'),
            // array('iso2' => 'TR', 'short_name' => 'Turkey'),
            // array('iso2' => 'TM', 'short_name' => 'Turkmenistan'),
            // array('iso2' => 'TC', 'short_name' => 'Turks and Caicos Islands'),
            // array('iso2' => 'TV', 'short_name' => 'Tuvalu'),
            // array('iso2' => 'UG', 'short_name' => 'Uganda'),
            // array('iso2' => 'UA', 'short_name' => 'Ukraine'),
            // array('iso2' => 'AE', 'short_name' => 'United Arab Emirates'),
            // array('iso2' => 'GB', 'short_name' => 'United Kingdom'),
            // array('iso2' => 'UM', 'short_name' => 'United States minor outlying islands'),
            // array('iso2' => 'UY', 'short_name' => 'Uruguay'),
            // array('iso2' => 'UZ', 'short_name' => 'Uzbekistan'),
            // array('iso2' => 'VU', 'short_name' => 'Vanuatu'),
            // array('iso2' => 'VA', 'short_name' => 'Vatican City State'),
            // array('iso2' => 'VE', 'short_name' => 'Venezuela'),
            // array('iso2' => 'VN', 'short_name' => 'Vietnam'),
            // array('iso2' => 'VG', 'short_name' => 'Virgin Islands (British)'),
            // array('iso2' => 'VI', 'short_name' => 'Virgin Islands (U.S.)'),
            // array('iso2' => 'WF', 'short_name' => 'Wallis and Futuna Islands'),
            // array('iso2' => 'EH', 'short_name' => 'Western Sahara'),
            // array('iso2' => 'YE', 'short_name' => 'Yemen'),
            // array('iso2' => 'YU', 'short_name' => 'Yugoslavia'),
            // array('iso2' => 'ZR', 'short_name' => 'Zaire'),
            // array('iso2' => 'ZM', 'short_name' => 'Zambia'),
            // array('iso2' => 'ZW', 'short_name' => 'Zimbabwe'),
    //    );

    //     Country::create($countries);
    }
    private function data()
    {
        return array(

        ['id' => '1', 'iso2' => 'ZW', 'short_name' => 'Zimbabwe'],
        ['id' => '2', 'iso2' => 'US', 'short_name' => 'United States'],
        ['id' => '3', 'iso2' => 'CA', 'short_name' => 'Canada'],
        ['id' => '4', 'iso2' => 'AF', 'short_name' => 'Afghanistan'],
        ['id' => '5', 'iso2' => 'AL', 'short_name' => 'Albania'],
        ['id' => '6', 'iso2' => 'DZ', 'short_name' => 'Algeria'],
        ['id' => '7', 'iso2' => 'AS', 'short_name' => 'American Samoa'],
        ['id' => '8', 'iso2' => 'AD', 'short_name' => 'Andorra'],
        ['id' => '9', 'iso2' => 'AO', 'short_name' => 'Angola'],
        ['id' => '10', 'iso2' => 'AI', 'short_name' => 'Anguilla'],
        ['id' => '11', 'iso2' => 'AQ', 'short_name' => 'Antarctica'],
        ['id' => '12', 'iso2' => 'AG', 'short_name' => 'Antigua and Barbuda'],
        ['id' => '13', 'iso2' => 'AR', 'short_name' => 'Argentina'],
        ['id' => '14', 'iso2' => 'AM', 'short_name' => 'Armenia'],
        ['id' => '15', 'iso2' => 'AW', 'short_name' => 'Aruba'],
        ['id' => '16', 'iso2' => 'AU', 'short_name' => 'Australia'],
        ['id' => '17', 'iso2' => 'AT', 'short_name' => 'Austria'],
        ['id' => '18', 'iso2' => 'AZ', 'short_name' => 'Azerbaijan'],
        ['id' => '19', 'iso2' => 'BS', 'short_name' => 'Bahamas'],
        ['id' => '20', 'iso2' => 'BH', 'short_name' => 'Bahrain'],
        ['id' => '21', 'iso2' => 'BD', 'short_name' => 'Bangladesh'],
        ['id' => '22', 'iso2' => 'BB', 'short_name' => 'Barbados'],
        ['id' => '23', 'iso2' => 'BY', 'short_name' => 'Belarus'],
        ['id' => '24', 'iso2' => 'BE', 'short_name' => 'Belgium'],
        ['id' => '25', 'iso2' => 'BZ', 'short_name' => 'Belize'],
        ['id' => '26', 'iso2' => 'BJ', 'short_name' => 'Benin'],
        ['id' => '27', 'iso2' => 'BM', 'short_name' => 'Bermuda'],
        ['id' => '28', 'iso2' => 'BT', 'short_name' => 'Bhutan'],
        ['id' => '29', 'iso2' => 'BO', 'short_name' => 'Bolivia'],
        ['id' => '30', 'iso2' => 'BA', 'short_name' => 'Bosnia and Herzegovina'],
        ['id' => '31', 'iso2' => 'BW', 'short_name' => 'Botswana'],
        ['id' => '32', 'iso2' => 'BV', 'short_name' => 'Bouvet Island'],
        ['id' => '33', 'iso2' => 'BR', 'short_name' => 'Brazil'],
        ['id' => '34', 'iso2' => 'IO', 'short_name' => 'British Indian Ocean Territory'],
        ['id' => '35', 'iso2' => 'BN', 'short_name' => 'Brunei Darussalam'],
        ['id' => '36', 'iso2' => 'BG', 'short_name' => 'Bulgaria'],
        ['id' => '37', 'iso2' => 'BF', 'short_name' => 'Burkina Faso'],
        ['id' => '38', 'iso2' => 'BI', 'short_name' => 'Burundi'],
        ['id' => '39', 'iso2' => 'KH', 'short_name' => 'Cambodia'],
        ['id' => '40', 'iso2' => 'CM', 'short_name' => 'Cameroon'],
        ['id' => '41', 'iso2' => 'CV', 'short_name' => 'Cape Verde'],
        ['id' => '42', 'iso2' => 'KY', 'short_name' => 'Cayman Islands'],
        ['id' => '43', 'iso2' => 'CF', 'short_name' => 'Central African Republic'],
        ['id' => '44', 'iso2' => 'TD', 'short_name' => 'Chad'],
        ['id' => '45', 'iso2' => 'CL', 'short_name' => 'Chile'],
        ['id' => '46', 'iso2' => 'CN', 'short_name' => 'China'],
        ['id' => '47', 'iso2' => 'CX', 'short_name' => 'Christmas Island'],
        ['id' => '48', 'iso2' => 'CC', 'short_name' => 'Cocos (Keeling) Islands'],
        ['id' => '49', 'iso2' => 'CO', 'short_name' => 'Colombia'],
        ['id' => '50', 'iso2' => 'KM', 'short_name' => 'Comoros'],
        ['id' => '51', 'iso2' => 'CG', 'short_name' => 'Congo'],
        ['id' => '52', 'iso2' => 'CK', 'short_name' => 'Cook Islands'],
        ['id' => '53', 'iso2' => 'CR', 'short_name' => 'Costa Rica'],
        ['id' => '54', 'iso2' => 'HR', 'short_name' => 'Croatia (Hrvatska)'],
        ['id' => '55', 'iso2' => 'CU', 'short_name' => 'Cuba'],
        ['id' => '56', 'iso2' => 'CY', 'short_name' => 'Cyprus'],
        ['id' => '57', 'iso2' => 'CZ', 'short_name' => 'Czech Republic'],
        ['id' => '58', 'iso2' => 'CD', 'short_name' => 'Democratic Republic of Congo'],
        ['id' => '59', 'iso2' => 'DK', 'short_name' => 'Denmark'],
        ['id' => '60', 'iso2' => 'DJ', 'short_name' => 'Djibouti'],
        ['id' => '61', 'iso2' => 'DM', 'short_name' => 'Dominica'],
        ['id' => '62', 'iso2' => 'DO', 'short_name' => 'Dominican Republic'],
        ['id' => '63', 'iso2' => 'TP', 'short_name' => 'East Timor'],
        ['id' => '64', 'iso2' => 'EC', 'short_name' => 'Ecuador'],
        ['id' => '65', 'iso2' => 'EG', 'short_name' => 'Egypt'],
        ['id' => '66', 'iso2' => 'SV', 'short_name' => 'El Salvador'],
        ['id' => '67', 'iso2' => 'GQ', 'short_name' => 'Equatorial Guinea'],
        ['id' => '68', 'iso2' => 'ER', 'short_name' => 'Eritrea'],
        ['id' => '69', 'iso2' => 'EE', 'short_name' => 'Estonia'],
        ['id' => '70', 'iso2' => 'ET', 'short_name' => 'Ethiopia'],
        ['id' => '71', 'iso2' => 'FK', 'short_name' => 'Falkland Islands (Malvinas)'],
        ['id' => '72', 'iso2' => 'FO', 'short_name' => 'Faroe Islands'],
        ['id' => '73', 'iso2' => 'FJ', 'short_name' => 'Fiji'],
        ['id' => '74', 'iso2' => 'FI', 'short_name' => 'Finland'],
        ['id' => '75', 'iso2' => 'FR', 'short_name' => 'France'],
        ['id' => '76', 'iso2' => 'FX', 'short_name' => 'France, Metropolitan'],
        ['id' => '77', 'iso2' => 'GF', 'short_name' => 'French Guiana'],
        ['id' => '78', 'iso2' => 'PF', 'short_name' => 'French Polynesia'],
        ['id' => '79', 'iso2' => 'TF', 'short_name' => 'French Southern Territories'],
        ['id' => '80', 'iso2' => 'GA', 'short_name' => 'Gabon'],
        ['id' => '81', 'iso2' => 'GM', 'short_name' => 'Gambia'],
        ['id' => '82', 'iso2' => 'GE', 'short_name' => 'Georgia'],
        ['id' => '83', 'iso2' => 'DE', 'short_name' => 'Germany'],
        ['id' => '84', 'iso2' => 'GH', 'short_name' => 'Ghana'],
        ['id' => '85', 'iso2' => 'GI', 'short_name' => 'Gibraltar'],
        ['id' => '86', 'iso2' => 'GR', 'short_name' => 'Greece'],
        ['id' => '87', 'iso2' => 'GL', 'short_name' => 'Greenland'],
        ['id' => '88', 'iso2' => 'GD', 'short_name' => 'Grenada'],
        ['id' => '89', 'iso2' => 'GP', 'short_name' => 'Guadeloupe'],
        ['id' => '90', 'iso2' => 'GU', 'short_name' => 'Guam'],
        ['id' => '91', 'iso2' => 'GT', 'short_name' => 'Guatemala'],
        ['id' => '92', 'iso2' => 'GN', 'short_name' => 'Guinea'],
        ['id' => '93', 'iso2' => 'GW', 'short_name' => 'Guinea-Bissau'],
        ['id' => '94', 'iso2' => 'GY', 'short_name' => 'Guyana'],
        ['id' => '95', 'iso2' => 'HT', 'short_name' => 'Haiti'],
        ['id' => '96', 'iso2' => 'HM', 'short_name' => 'Heard and Mc Donald Islands'],
        ['id' => '97', 'iso2' => 'HN', 'short_name' => 'Honduras'],
        ['id' => '98', 'iso2' => 'HK', 'short_name' => 'Hong Kong'],
        ['id' => '99', 'iso2' => 'HU', 'short_name' => 'Hungary'],
        ['id' => '100', 'iso2' => 'IS', 'short_name' => 'Iceland'],
        ['id' => '101', 'iso2' => 'IN', 'short_name' => 'India'],
        ['id' => '102', 'iso2' => 'IM', 'short_name' => 'Isle of Man'],
        ['id' => '103', 'iso2' => 'ID', 'short_name' => 'Indonesia'],
        ['id' => '104', 'iso2' => 'IR', 'short_name' => 'Iran (Islamic Republic of)'],
        ['id' => '105', 'iso2' => 'IQ', 'short_name' => 'Iraq'],
        ['id' => '106', 'iso2' => 'IE', 'short_name' => 'Ireland'],
        ['id' => '107', 'iso2' => 'IL', 'short_name' => 'Israel'],
        ['id' => '108', 'iso2' => 'IT', 'short_name' => 'Italy'],
        ['id' => '109', 'iso2' => 'CI', 'short_name' => 'Ivory Coast'],
        ['id' => '110', 'iso2' => 'JE', 'short_name' => 'Jersey'],
        ['id' => '111', 'iso2' => 'JM', 'short_name' => 'Jamaica'],
        ['id' => '112', 'iso2' => 'JP', 'short_name' => 'Japan'],
        ['id' => '113', 'iso2' => 'JO', 'short_name' => 'Jordan'],
        ['id' => '114', 'iso2' => 'KZ', 'short_name' => 'Kazakhstan'],
        ['id' => '115', 'iso2' => 'KE', 'short_name' => 'Kenya'],
        ['id' => '116', 'iso2' => 'KI', 'short_name' => 'Kiribati'],
        ['id' => '117', 'iso2' => 'KP', 'short_name' => 'Korea, Democratic People\'s Republic of'],
        ['id' => '118', 'iso2' => 'KR', 'short_name' => 'Korea, Republic of'],
        ['id' => '119', 'iso2' => 'KW', 'short_name' => 'Kuwait'],
        ['id' => '120', 'iso2' => 'KG', 'short_name' => 'Kyrgyzstan'],
        ['id' => '121', 'iso2' => 'LA', 'short_name' => 'Lao People\'s Democratic Republic'],
        ['id' => '122', 'iso2' => 'LV', 'short_name' => 'Latvia'],
        ['id' => '123', 'iso2' => 'LB', 'short_name' => 'Lebanon'],
        ['id' => '124', 'iso2' => 'LS', 'short_name' => 'Lesotho'],
        ['id' => '125', 'iso2' => 'LR', 'short_name' => 'Liberia'],
        ['id' => '126', 'iso2' => 'LY', 'short_name' => 'Libyan Arab Jamahiriya'],
        ['id' => '127', 'iso2' => 'LI', 'short_name' => 'Liechtenstein'],
        ['id' => '128', 'iso2' => 'LT', 'short_name' => 'Lithuania'],
        ['id' => '129', 'iso2' => 'LU', 'short_name' => 'Luxembourg'],
        ['id' => '130', 'iso2' => 'MO', 'short_name' => 'Macau'],
        ['id' => '131', 'iso2' => 'MK', 'short_name' => 'North Macedonia'],
        ['id' => '132', 'iso2' => 'MG', 'short_name' => 'Madagascar'],
        ['id' => '133', 'iso2' => 'MW', 'short_name' => 'Malawi'],
        ['id' => '134', 'iso2' => 'MY', 'short_name' => 'Malaysia'],
        ['id' => '135', 'iso2' => 'MV', 'short_name' => 'Maldives'],
        ['id' => '136', 'iso2' => 'ML', 'short_name' => 'Mali'],
        ['id' => '137', 'iso2' => 'MT', 'short_name' => 'Malta'],
        ['id' => '138', 'iso2' => 'MH', 'short_name' => 'Marshall Islands'],
        ['id' => '139', 'iso2' => 'MQ', 'short_name' => 'Martinique'],
        ['id' => '140', 'iso2' => 'MR', 'short_name' => 'Mauritania'],
        ['id' => '141', 'iso2' => 'MU', 'short_name' => 'Mauritius'],
        ['id' => '142', 'iso2' => 'TY', 'short_name' => 'Mayotte'],
        ['id' => '143', 'iso2' => 'MX', 'short_name' => 'Mexico'],
        ['id' => '144', 'iso2' => 'FM', 'short_name' => 'Micronesia, Federated States of'],
        ['id' => '145', 'iso2' => 'MD', 'short_name' => 'Moldova, Republic of'],
        ['id' => '146', 'iso2' => 'MC', 'short_name' => 'Monaco'],
        ['id' => '147', 'iso2' => 'MN', 'short_name' => 'Mongolia'],
        ['id' => '148', 'iso2' => 'ME', 'short_name' => 'Montenegro'],
        ['id' => '149', 'iso2' => 'MS', 'short_name' => 'Montserrat'],
        ['id' => '150', 'iso2' => 'MA', 'short_name' => 'Morocco'],
        ['id' => '151', 'iso2' => 'MZ', 'short_name' => 'Mozambique'],
        ['id' => '152', 'iso2' => 'MM', 'short_name' => 'Myanmar'],
        ['id' => '153', 'iso2' => 'NA', 'short_name' => 'Namibia'],
        ['id' => '154', 'iso2' => 'NR', 'short_name' => 'Nauru'],
        ['id' => '155', 'iso2' => 'NP', 'short_name' => 'Nepal'],
        ['id' => '156', 'iso2' => 'NL', 'short_name' => 'Netherlands'],
        ['id' => '157', 'iso2' => 'AN', 'short_name' => 'Netherlands Antilles'],
        ['id' => '158', 'iso2' => 'NC', 'short_name' => 'New Caledonia'],
        ['id' => '159', 'iso2' => 'NZ', 'short_name' => 'New Zealand'],
        ['id' => '160', 'iso2' => 'NI', 'short_name' => 'Nicaragua'],
        ['id' => '161', 'iso2' => 'NE', 'short_name' => 'Niger'],
        ['id' => '162', 'iso2' => 'NG', 'short_name' => 'Nigeria'],
        ['id' => '163', 'iso2' => 'NU', 'short_name' => 'Niue'],
        ['id' => '164', 'iso2' => 'NF', 'short_name' => 'Norfolk Island'],
        ['id' => '165', 'iso2' => 'MP', 'short_name' => 'Northern Mariana Islands'],
        ['id' => '166', 'iso2' => 'NO', 'short_name' => 'Norway'],
        ['id' => '167', 'iso2' => 'OM', 'short_name' => 'Oman'],
        ['id' => '168', 'iso2' => 'PK', 'short_name' => 'Pakistan'],
        ['id' => '169', 'iso2' => 'PW', 'short_name' => 'Palau'],
        ['id' => '170', 'iso2' => 'PS', 'short_name' => 'Palestine'],
        ['id' => '171', 'iso2' => 'PA', 'short_name' => 'Panama'],
        ['id' => '172', 'iso2' => 'PG', 'short_name' => 'Papua New Guinea'],
        ['id' => '173', 'iso2' => 'PY', 'short_name' => 'Paraguay'],
        ['id' => '174', 'iso2' => 'PE', 'short_name' => 'Peru'],
        ['id' => '175', 'iso2' => 'PH', 'short_name' => 'Philippines'],
        ['id' => '176', 'iso2' => 'PN', 'short_name' => 'Pitcairn'],
        ['id' => '177', 'iso2' => 'PL', 'short_name' => 'Poland'],
        ['id' => '178', 'iso2' => 'PT', 'short_name' => 'Portugal'],
        ['id' => '179', 'iso2' => 'PR', 'short_name' => 'Puerto Rico'],
        ['id' => '180', 'iso2' => 'QA', 'short_name' => 'Qatar'],
        ['id' => '181', 'iso2' => 'RE', 'short_name' => 'Reunion'],
        ['id' => '182', 'iso2' => 'RO', 'short_name' => 'Romania'],
        ['id' => '183', 'iso2' => 'RU', 'short_name' => 'Russian Federation'],
        ['id' => '184', 'iso2' => 'RW', 'short_name' => 'Rwanda'],
        ['id' => '185', 'iso2' => 'KN', 'short_name' => 'Saint Kitts and Nevis'],
        ['id' => '186', 'iso2' => 'LC', 'short_name' => 'Saint Lucia'],
        ['id' => '187', 'iso2' => 'VC', 'short_name' => 'Saint Vincent and the Grenadines'],
        ['id' => '188', 'iso2' => 'WS', 'short_name' => 'Samoa'],
        ['id' => '189', 'iso2' => 'SM', 'short_name' => 'San Marino'],
        ['id' => '190', 'iso2' => 'ST', 'short_name' => 'Sao Tome and Principe'],
        ['id' => '191', 'iso2' => 'SA', 'short_name' => 'Saudi Arabia'],
        ['id' => '192', 'iso2' => 'SN', 'short_name' => 'Senegal'],
        ['id' => '193', 'iso2' => 'RS', 'short_name' => 'Serbia'],
        ['id' => '194', 'iso2' => 'SC', 'short_name' => 'Seychelles'],
        ['id' => '195', 'iso2' => 'SL', 'short_name' => 'Sierra Leone'],
        ['id' => '196', 'iso2' => 'SG', 'short_name' => 'Singapore'],
        ['id' => '197', 'iso2' => 'SK', 'short_name' => 'Slovakia'],
        ['id' => '198', 'iso2' => 'SI', 'short_name' => 'Slovenia'],
        ['id' => '199', 'iso2' => 'SB', 'short_name' => 'Solomon Islands'],
        ['id' => '200', 'iso2' => 'SO', 'short_name' => 'Somalia'],
        ['id' => '201', 'iso2' => 'ZA', 'short_name' => 'South Africa'],
        ['id' => '202', 'iso2' => 'GS', 'short_name' => 'South Georgia South Sandwich Islands'],
        ['id' => '203', 'iso2' => 'SS', 'short_name' => 'South Sudan'],
        ['id' => '204', 'iso2' => 'ES', 'short_name' => 'Spain'],
        ['id' => '205', 'iso2' => 'LK', 'short_name' => 'Sri Lanka'],
        ['id' => '206', 'iso2' => 'SH', 'short_name' => 'St. Helena'],
        ['id' => '207', 'iso2' => 'PM', 'short_name' => 'St. Pierre and Miquelon'],
        ['id' => '208', 'iso2' => 'SD', 'short_name' => 'Sudan'],
        ['id' => '209', 'iso2' => 'SR', 'short_name' => 'Suriname'],
        ['id' => '210', 'iso2' => 'SJ', 'short_name' => 'Svalbard and Jan Mayen Islands'],
        ['id' => '211', 'iso2' => 'SZ', 'short_name' => 'Swaziland'],
        ['id' => '212', 'iso2' => 'SE', 'short_name' => 'Sweden'],
        ['id' => '213', 'iso2' => 'CH', 'short_name' => 'Switzerland'],
        ['id' => '214', 'iso2' => 'SY', 'short_name' => 'Syrian Arab Republic'],
        ['id' => '215', 'iso2' => 'TW', 'short_name' => 'Taiwan'],
        ['id' => '216', 'iso2' => 'TJ', 'short_name' => 'Tajikistan'],
        ['id' => '217', 'iso2' => 'TZ', 'short_name' => 'Tanzania, United Republic of'],
        ['id' => '218', 'iso2' => 'TH', 'short_name' => 'Thailand'],
        ['id' => '219', 'iso2' => 'TG', 'short_name' => 'Togo'],
        ['id' => '220', 'iso2' => 'TK', 'short_name' => 'Tokelau'],
        ['id' => '221', 'iso2' => 'TO', 'short_name' => 'Tonga'],
        ['id' => '222', 'iso2' => 'TT', 'short_name' => 'Trinidad and Tobago'],
        ['id' => '223', 'iso2' => 'TN', 'short_name' => 'Tunisia'],
        ['id' => '224', 'iso2' => 'TR', 'short_name' => 'Turkey'],
        ['id' => '225', 'iso2' => 'TM', 'short_name' => 'Turkmenistan'],
        ['id' => '226', 'iso2' => 'TC', 'short_name' => 'Turks and Caicos Islands'],
        ['id' => '227', 'iso2' => 'TV', 'short_name' => 'Tuvalu'],
        ['id' => '228', 'iso2' => 'UG', 'short_name' => 'Uganda'],
        ['id' => '229', 'iso2' => 'UA', 'short_name' => 'Ukraine'],
        ['id' => '230', 'iso2' => 'AE', 'short_name' => 'United Arab Emirates'],
        ['id' => '231', 'iso2' => 'GB', 'short_name' => 'United Kingdom'],
        ['id' => '232', 'iso2' => 'UM', 'short_name' => 'United States minor outlying islands'],
        ['id' => '233', 'iso2' => 'UY', 'short_name' => 'Uruguay'],
        ['id' => '234', 'iso2' => 'UZ', 'short_name' => 'Uzbekistan'],
        ['id' => '235', 'iso2' => 'VU', 'short_name' => 'Vanuatu'],
        ['id' => '236', 'iso2' => 'VA', 'short_name' => 'Vatican City State'],
        ['id' => '237', 'iso2' => 'VE', 'short_name' => 'Venezuela'],
        ['id' => '238', 'iso2' => 'VN', 'short_name' => 'Vietnam'],
        ['id' => '239', 'iso2' => 'VG', 'short_name' => 'Virgin Islands (British)'],
        ['id' => '240', 'iso2' => 'VI', 'short_name' => 'Virgin Islands (U.S.)'],
        ['id' => '241', 'iso2' => 'WF', 'short_name' => 'Wallis and Futuna Islands'],
        ['id' => '242', 'iso2' => 'EH', 'short_name' => 'Western Sahara'],
        ['id' => '243', 'iso2' => 'YE', 'short_name' => 'Yemen'],
        ['id' => '244', 'iso2' => 'YU', 'short_name' => 'Yugoslavia'],
        ['id' => '245', 'iso2' => 'ZR', 'short_name' => 'Zaire'],
        ['id' => '246', 'iso2' => 'ZM', 'short_name' => 'Zambia'],
           
        );
    }
}
